/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctioncontractSol from "./auctioncontract.sol";
export type { auctioncontractSol };
export type { Lock } from "./Lock";
